{"nbformat":4,"nbformat_minor":0,"metadata":{"accelerator":"GPU","colab":{"name":"first_trainer_counting.ipynb","provenance":[],"collapsed_sections":[],"machine_shape":"hm","mount_file_id":"1CaixTlTqEQSoYMgK6aidoLCg43uxgge_","authorship_tag":"ABX9TyOGKYT2itEhGawzXIXQBrF3"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.3"}},"cells":[{"cell_type":"code","metadata":{"colab_type":"code","executionInfo":{"status":"ok","timestamp":1589142735683,"user_tz":-120,"elapsed":1712,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"id":"spDiWJ97I0vZ","outputId":"20c892a5-7a1e-4483-a322-db8be33472e1","colab":{"base_uri":"https://localhost:8080/","height":326}},"source":["# %cd ..\n","!nvidia-smi"],"execution_count":1,"outputs":[{"output_type":"stream","text":["Sun May 10 20:32:16 2020       \n","+-----------------------------------------------------------------------------+\n","| NVIDIA-SMI 440.82       Driver Version: 418.67       CUDA Version: 10.1     |\n","|-------------------------------+----------------------+----------------------+\n","| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |\n","| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\n","|===============================+======================+======================|\n","|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |\n","| N/A   44C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |\n","+-------------------------------+----------------------+----------------------+\n","                                                                               \n","+-----------------------------------------------------------------------------+\n","| Processes:                                                       GPU Memory |\n","|  GPU       PID   Type   Process name                             Usage      |\n","|=============================================================================|\n","|  No running processes found                                                 |\n","+-----------------------------------------------------------------------------+\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab_type":"code","id":"j5KSeQKwuZYB","outputId":"a8f78ced-9df0-4a3c-9599-e1431c16da01","executionInfo":{"status":"ok","timestamp":1589142839420,"user_tz":-120,"elapsed":105440,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["!pip install gdown\n","!pip install tensorflow-gpu --user\n","!pip install --upgrade keras"],"execution_count":2,"outputs":[{"output_type":"stream","text":["Requirement already satisfied: gdown in /usr/local/lib/python3.6/dist-packages (3.6.4)\n","Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from gdown) (1.12.0)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from gdown) (4.41.1)\n","Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from gdown) (2.23.0)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (1.24.3)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (3.0.4)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (2020.4.5.1)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (2.9)\n","Collecting tensorflow-gpu\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/31/bf/c28971266ca854a64f4b26f07c4112ddd61f30b4d1f18108b954a746f8ea/tensorflow_gpu-2.2.0-cp36-cp36m-manylinux2010_x86_64.whl (516.2MB)\n","\u001b[K     |████████████████████████████████| 516.2MB 31kB/s \n","\u001b[?25hRequirement already satisfied: tensorboard<2.3.0,>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (2.2.1)\n","Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.1.0)\n","Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.12.0)\n","Requirement already satisfied: gast==0.3.3 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (0.3.3)\n","Requirement already satisfied: google-pasta>=0.1.8 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (0.2.0)\n","Requirement already satisfied: keras-preprocessing>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.1.0)\n","Requirement already satisfied: numpy<2.0,>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.18.4)\n","Requirement already satisfied: tensorflow-estimator<2.3.0,>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (2.2.0)\n","Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (0.9.0)\n","Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.12.1)\n","Requirement already satisfied: astunparse==1.6.3 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.6.3)\n","Requirement already satisfied: wheel>=0.26; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (0.34.2)\n","Requirement already satisfied: h5py<2.11.0,>=2.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (2.10.0)\n","Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.28.1)\n","Requirement already satisfied: scipy==1.4.1; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.4.1)\n","Requirement already satisfied: protobuf>=3.8.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (3.10.0)\n","Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (3.2.1)\n","Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (1.0.1)\n","Requirement already satisfied: google-auth<2,>=1.6.3 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (1.7.2)\n","Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (3.2.1)\n","Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (1.6.0.post3)\n","Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (0.4.1)\n","Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (2.23.0)\n","Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (46.1.3)\n","Requirement already satisfied: cachetools<3.2,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (3.1.1)\n","Requirement already satisfied: rsa<4.1,>=3.1.4 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (4.0)\n","Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (0.2.8)\n","Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (1.3.0)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (2.9)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (1.24.3)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (3.0.4)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (2020.4.5.1)\n","Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.6/dist-packages (from rsa<4.1,>=3.1.4->google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (0.4.8)\n","Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu) (3.1.0)\n","Installing collected packages: tensorflow-gpu\n","\u001b[33m  WARNING: The scripts estimator_ckpt_converter, saved_model_cli, tensorboard, tf_upgrade_v2, tflite_convert, toco and toco_from_protos are installed in '/root/.local/bin' which is not on PATH.\n","  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\n","Successfully installed tensorflow-gpu-2.2.0\n","Requirement already up-to-date: keras in /usr/local/lib/python3.6/dist-packages (2.3.1)\n","Requirement already satisfied, skipping upgrade: h5py in /usr/local/lib/python3.6/dist-packages (from keras) (2.10.0)\n","Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in /usr/local/lib/python3.6/dist-packages (from keras) (1.18.4)\n","Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python3.6/dist-packages (from keras) (3.13)\n","Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from keras) (1.1.0)\n","Requirement already satisfied, skipping upgrade: scipy>=0.14 in /usr/local/lib/python3.6/dist-packages (from keras) (1.4.1)\n","Requirement already satisfied, skipping upgrade: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from keras) (1.12.0)\n","Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from keras) (1.0.8)\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"33KexW3M7xhZ","colab_type":"code","outputId":"49b98a64-3ec2-46a9-9ce1-3cdbaaa433ab","executionInfo":{"status":"ok","timestamp":1589142847770,"user_tz":-120,"elapsed":113775,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"colab":{"base_uri":"https://localhost:8080/","height":272}},"source":["#quickfix error in callbacks of keras, pullrequest is already open in github\n","#later versions of tensorflow and keras should contain this fix\n","%cd ../../../\n","from google.colab import files\n","import shutil\n","%cd root/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/\n","# files.download('callbacks.py')\n","!rm callbacks.py\n","shutil.copyfile('/content/drive/My Drive/person_detection/utils/callbacks.py', \n","                './callbacks.py')\n","!ls\n","\n"],"execution_count":3,"outputs":[{"output_type":"stream","text":["/\n","[Errno 2] No such file or directory: 'root/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/'\n","/\n","rm: cannot remove 'callbacks.py': No such file or directory\n","bin\t\t\t\t\t   lib\t  srv\n","boot\t\t\t\t\t   lib32  swift\n","callbacks.py\t\t\t\t   lib64  sys\n","content\t\t\t\t\t   media  tensorflow-1.15.2\n","datalab\t\t\t\t\t   mnt\t  tmp\n","dev\t\t\t\t\t   opt\t  tools\n","dlib-19.18.0-cp27-cp27mu-linux_x86_64.whl  proc   usr\n","dlib-19.18.0-cp36-cp36m-linux_x86_64.whl   root   var\n","etc\t\t\t\t\t   run\n","home\t\t\t\t\t   sbin\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"4-5gt6xM8Kjd","colab_type":"text"},"source":["# Imports"]},{"cell_type":"code","metadata":{"id":"FaPos3qf8KFs","colab_type":"code","outputId":"a42d4dc2-dd81-4572-e9d4-467e6768d90b","executionInfo":{"status":"ok","timestamp":1589142849866,"user_tz":-120,"elapsed":115859,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"colab":{"base_uri":"https://localhost:8080/","height":54}},"source":["from pandas.plotting import register_matplotlib_converters\n","import seaborn as sns\n","from matplotlib import rc\n","from pylab import rcParams\n","from IPython.display import Image\n","import os \n","from datetime import datetime\n","\n","%matplotlib notebook\n","%config InlineBackend.figure_format='retina'\n","\n","register_matplotlib_converters()\n","sns.set(style='whitegrid', palette='muted', font_scale=1.5)\n","\n","rcParams['figure.figsize'] = 22, 10\n"],"execution_count":4,"outputs":[{"output_type":"stream","text":["/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.\n","  import pandas.util.testing as tm\n"],"name":"stderr"}]},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"J8LEtNbNn7Ri"},"source":["# Training\n","\n"]},{"cell_type":"code","metadata":{"colab_type":"code","id":"A-DO3mGwqq0i","colab":{}},"source":["logdir = '/content/drive/My\\ Drive/person_counting/tensorboard/colab_{}_trainer_nr_1/'.format(datetime.now().strftime(\"%Y-%m-%d-%H-%M-%S\"))\n","top_path = '/content/drive/My\\ Drive/person_detection/pcds_dataset_detections/pcds_dataset_detected/'"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"do7gLVqi_jNB","colab_type":"code","outputId":"e19181f6-7021-4b82-c898-928df2698c9d","executionInfo":{"status":"ok","timestamp":1589142849883,"user_tz":-120,"elapsed":115863,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"colab":{"base_uri":"https://localhost:8080/","height":35}},"source":["%cd /content/drive/My\\ Drive/"],"execution_count":6,"outputs":[{"output_type":"stream","text":["/content/drive/My Drive\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"E8ep37lYAEkX","colab_type":"code","outputId":"c2d9b158-e3bb-41fd-d4f5-f9abb98a6d92","colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["!python -m person_counting.models.cnn_regression  --top-path {top_path}\\\n","                                                  --topdir-log {logdir} \\\n","                                                  --n-runs 100 \\\n","                                                  --top-path {top_path}\\\n","                                                  --augmentation-factor 0\\\n","                                                  --filter-hour-above 21\\\n","                                                  --epochs 40\\"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Using TensorFlow backend.\n","Dataset contains: \n","735 training csvs \n","318 testing csvs\n","Using rescale factor  [0.11111111]\n","2020-05-10 20:55:47.771360: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-05-10 20:55:47.787144: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 20:55:47.788129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-05-10 20:55:47.788505: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-05-10 20:55:47.793664: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-05-10 20:55:47.796365: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-05-10 20:55:47.796799: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-05-10 20:55:47.799107: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-05-10 20:55:47.799933: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-05-10 20:55:47.803366: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-05-10 20:55:47.803511: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 20:55:47.804456: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 20:55:47.805398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-05-10 20:55:47.805701: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n","2020-05-10 20:55:47.810687: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-05-10 20:55:47.811020: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ee7800 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-05-10 20:55:47.811058: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-05-10 20:55:47.901400: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 20:55:47.902669: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ee7640 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2020-05-10 20:55:47.902764: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0\n","2020-05-10 20:55:47.903030: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 20:55:47.903932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-05-10 20:55:47.904002: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-05-10 20:55:47.904035: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-05-10 20:55:47.904063: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-05-10 20:55:47.904100: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-05-10 20:55:47.904128: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-05-10 20:55:47.904155: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-05-10 20:55:47.904183: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-05-10 20:55:47.904285: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 20:55:47.905219: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 20:55:47.906069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-05-10 20:55:47.906136: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-05-10 20:55:47.907817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-05-10 20:55:47.907851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 \n","2020-05-10 20:55:47.907867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N \n","2020-05-10 20:55:47.908046: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 20:55:47.908922: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 20:55:47.909721: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2020-05-10 20:55:47.909767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15056 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)\n","Tried to create a Pool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Tried to create a Pool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Model: \"sequential_1\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","average_pooling2d_2 (Average (None, 250, 10, 1)        0         \n","_________________________________________________________________\n","conv2d_1 (Conv2D)            (None, 247, 7, 6)         102       \n","_________________________________________________________________\n","average_pooling2d_1 (Average (None, 123, 3, 6)         0         \n","_________________________________________________________________\n","lambda_1 (Lambda)            (None, 123, 18)           0         \n","_________________________________________________________________\n","lstm_1 (LSTM)                (None, 123, 5)            480       \n","_________________________________________________________________\n","lstm_2 (LSTM)                (None, 5)                 220       \n","_________________________________________________________________\n","dense_1 (Dense)              (None, 1)                 6         \n","=================================================================\n","Total params: 808\n","Trainable params: 808\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","units :  5\n","regularization :  0.01\n","pooling_type :  avg\n","pool_size_y :  2\n","pool_size_x :  2\n","optimizer :  SGD\n","learning_rate :  0.004131913953352232\n","layer_number :  1\n","kernel_size :  4\n","kernel_number :  6\n","filter_rows_lower :  150\n","filter_rows_factor :  1\n","filter_cols_upper :  35\n","filter_cols_lower :  25\n","batch_size :  32\n","batch_normalization :  False\n","filter_hour_above :  21\n","filter_category_noisy :  False\n","Generator contains  318  files with  9  batches of size  32\n","Generator contains  735  files with  22  batches of size  32\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/40\n","2020-05-10 20:56:07.432724: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-05-10 20:56:07.862622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","22/22 [==============================] - 38s 2s/step - loss: 0.3006 - mse: 0.0956 - msle: 0.0558 - mae_rescaled: 2.5071 - val_loss: 0.2855 - val_mse: 0.0854 - val_msle: 0.0493 - val_mae_rescaled: 2.3714\n","Epoch 2/40\n","22/22 [==============================] - 23s 1s/step - loss: 0.2876 - mse: 0.0863 - msle: 0.0497 - mae_rescaled: 2.3898 - val_loss: 0.2956 - val_mse: 0.0860 - val_msle: 0.0495 - val_mae_rescaled: 2.3881\n","Epoch 3/40\n"," 2/22 [=>............................] - ETA: 40s - loss: 0.2747 - mse: 0.0767 - msle: 0.0428 - mae_rescaled: 2.2739"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"1daIFw3ZzKK1","colab_type":"text"},"source":["# Training the best configuration and save some visualization\n","\n","Set the params for best configuration in the test_cnn.py file"]},{"cell_type":"code","metadata":{"id":"cjJj7xatld5v","colab_type":"code","outputId":"a8bac261-f350-4c78-b78e-cfd9b8888966","executionInfo":{"status":"ok","timestamp":1589125212110,"user_tz":-120,"elapsed":192424,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["!python -m person_counting.tests.test_cnn train_best_gpu"],"execution_count":0,"outputs":[{"output_type":"stream","text":["/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.\n","  import pandas.util.testing as tm\n","Using TensorFlow backend.\n","Dataset contains: \n","742 training csvs \n","319 testing csvs\n","2020-05-10 15:40:08.840918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-05-10 15:40:08.900606: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 15:40:08.901319: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-05-10 15:40:08.901760: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-05-10 15:40:09.160406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-05-10 15:40:09.296686: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-05-10 15:40:09.324502: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-05-10 15:40:09.597866: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-05-10 15:40:09.627544: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-05-10 15:40:10.136210: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-05-10 15:40:10.136435: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 15:40:10.137156: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 15:40:10.137736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-05-10 15:40:10.138070: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n","2020-05-10 15:40:10.142847: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2200000000 Hz\n","2020-05-10 15:40:10.143149: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2ef3480 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-05-10 15:40:10.143185: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-05-10 15:40:10.261031: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 15:40:10.261779: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2ef32c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2020-05-10 15:40:10.261808: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0\n","2020-05-10 15:40:10.263060: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 15:40:10.263595: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-05-10 15:40:10.263697: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-05-10 15:40:10.263731: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-05-10 15:40:10.263747: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-05-10 15:40:10.263765: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-05-10 15:40:10.263780: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-05-10 15:40:10.263794: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-05-10 15:40:10.263810: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-05-10 15:40:10.263874: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 15:40:10.264398: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 15:40:10.264890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-05-10 15:40:10.264971: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-05-10 15:40:10.266348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-05-10 15:40:10.266375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 \n","2020-05-10 15:40:10.266383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N \n","2020-05-10 15:40:10.266529: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 15:40:10.267114: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-05-10 15:40:10.267670: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2020-05-10 15:40:10.267711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15056 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)\n","Tried to create a Pool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Tried to create a Pool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Traceback (most recent call last):\n","  File \"/usr/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n","    \"__main__\", mod_spec)\n","  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n","    exec(code, run_globals)\n","  File \"/content/drive/My Drive/person_counting/tests/test_cnn.py\", line 242, in <module>\n","    main()\n","  File \"/content/drive/My Drive/person_counting/tests/test_cnn.py\", line 36, in main\n","    train_best(workers, multi_processing, top_path, ipython_mode)\n","  File \"/content/drive/My Drive/person_counting/tests/test_cnn.py\", line 192, in train_best\n","    cnn_model = cnn.create_cnn(timestep_num, feature_num, hparams)\n","  File \"/content/drive/My Drive/person_counting/models/cnn_regression.py\", line 175, in create_cnn\n","    model.add(LSTM(units=hparams['units'],activation='relu', return_sequences=True))\n","KeyError: 'units'\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"iUCR-WDv6MGP","colab_type":"text"},"source":["# Visualization of last run"]},{"cell_type":"code","metadata":{"id":"wsPZOnXvO-k5","colab_type":"code","colab":{}},"source":["image_path = '/content/drive/My Drive/person_counting/visualizations'\n","for image_name in os.listdir(image_path):\n","  if image_name[-4:] == '.png':\n","    print()\n","    Image(os.path.join(image_path, image_name))"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"No4lDhTw7PGc","colab_type":"text"},"source":["#Utils"]},{"cell_type":"code","metadata":{"id":"kOfBHA8FTVdB","colab_type":"code","colab":{}},"source":["# use this code to prevent colab from disconnecting during longer training times in javascript console window (not in colab cell)\n","function ClickConnect(){\n","    console.log(\"Clicked on connect button\"); \n","    document.querySelector(\"colab-connect-button\").click()\n","}\n","setInterval(ClickConnect, 60000)"],"execution_count":0,"outputs":[]}]}